set_alarm:
  name: Set Alarm
  description: Set the alarm time and activate the alarm.
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: alarm_clock
          domain: switch
    time:
      name: Time
      description: >
        Time to set the alarm for.
        Supports both time picker and text input (e.g., "7:00" or "7 in the morning")
      required: true
      example: "07:00"
      selector:
        text:

snooze:
  name: Snooze Alarm
  description: Snooze the currently active alarm.
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: alarm_clock
          domain: switch

stop:
  name: Stop Alarm
  description: Stop the currently active alarm.
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: alarm_clock
          domain: switch