set_alarm:
  name: Set Alarm
  description: >
    Set the alarm time. If the time is in the past, it will automatically be set for tomorrow.
    If the time is in the future, it will be set for today.
  fields:
    time:
      name: Time
      description: Time to set the alarm (format HH:MM:SS, HH:MM, or HHMM)
      example: "07:00:00"
      required: true
      selector:
        time: {}

snooze:
  name: Snooze
  description: Snooze the alarm for the configured duration
  target:
    entity:
      integration: alarm_clock
      domain: switch

stop:
  name: Stop
  description: Stop the current alarm
  target:
    entity:
      integration: alarm_clock
      domain: switch