set_alarm:
  name: Set Alarm
  description: Set the alarm time and activate the alarm.
  target:
    entity:
      integration: alarm_clock
      domain: switch
  fields:
    time:
      name: Time
      description: "The time to set the alarm for (format: HH:MM or HH:MM:SS)"
      required: true
      example: "07:00"
      selector:
        time:
          enable_time: true

snooze:
  name: Snooze Alarm
  description: Snooze the currently active alarm.
  target:
    entity:
      integration: alarm_clock
      domain: switch
      multiple: false
  fields: {}

stop:
  name: Stop Alarm
  description: Stop the currently active alarm.
  target:
    entity:
      integration: alarm_clock
      domain: switch
      multiple: false
  fields: {}