set_alarm:
  fields:
    entity_id:
      example: "datetime.alarm_time"
      required: true
      selector:
        entity:
          integration: alarm_clock
          domain: datetime
    time:
      example: "07:00"
      required: true
      selector:
        text:

snooze:
  fields:
    entity_id:
      example: "switch.alarm"
      required: true
      selector:
        entity:
          integration: alarm_clock
          domain: switch

stop:
  fields:
    entity_id:
      example: "switch.alarm"
      required: true
      selector:
        entity:
          integration: alarm_clock
          domain: switch