set_alarm:
  name: Set Alarm
  description: Set the alarm time.
  target:
    entity:
      domain: datetime
      integration: alarm_clock
    device:
      integration: alarm_clock
    area: {}
  fields:
    time:
      name: Time
      description: Time to set (examples: 07:00, 7, 0700)
      required: true
      example: "07:00"
      selector:
        text:
          type: text

snooze:
  name: Snooze
  description: Snooze the alarm.
  target:
    entity:
      domain: switch
      integration: alarm_clock
    device:
      integration: alarm_clock
    area: {}
stop:
  name: Stop
  description: Stop the alarm.
  target:
    entity:
      domain: switch
      integration: alarm_clock
    device:
      integration: alarm_clock
    area: {}