set_alarm:
  name: Set Alarm
  description: >
    Set the alarm time. Accepts formats: HH:MM:SS, HH:MM, H:MM, HHMM, or just H (e.g., 7 for 07:00).
  target:
    entity:
      domain: datetime
      integration: alarm_clock
  fields:
    time:
      name: Time
      description: "Time to set (examples: 07:00, 7, 0700)"
      required: true
      selector:
        time: {}

snooze:
  name: Snooze
  description: Snooze the alarm for the configured duration
  target:
    entity:
      integration: alarm_clock
      domain: switch

stop:
  name: Stop
  description: Stop the current alarm
  target:
    entity:
      integration: alarm_clock
      domain: switch