blueprint:
  name: "[Voice] Stel wekker in"
  description: Stel wekker in
  domain: automation
  input:
    time:
      name: Tijd
      description: Tijdstip van de wekker (bijv. 7:00, 14:30, 7 uur 's ochtends, over 10 minuten, over 2 uur)
      required: true
      selector:
        text: {}
  trigger:
    - platform: conversation
      command:
        - (Stel | Zet) (een | het) (wekker | alarm) (in |) (om | voor | op | over) {time}
        - (Wek | Maak me wakker) (om | voor | over) {time}
        - (Alarm | Wekker) (om | voor) {time}
        - Wek me 's ochtends om {time}
        - Maak me morgenochtend wakker om {time}
        - Wek me morgen om {time}
        - Maak me morgen wakker om {time}
  action:
    - choose:
        - conditions: "{{ 'over' in trigger.text }}"
          sequence:
            - variables:
                time_parts: "{{ trigger.time.split(' ') }}"
                time_value: "{{ time_parts[1] | int }}"
                time_unit: "{{ time_parts[2] | lower }}"
                now_timestamp: "{{ now().timestamp() }}"
            - choose:
                - conditions: "{{ time_unit == 'minuten' or time_unit == 'minuut' }}"
                  sequence:
                    - service: alarm_control_panel.set_alarm
                      target:
                        entity_id: alarm_control_panel.alarm_panel # VERVANG DIT!
                      data:
                        time: "{{ (now_timestamp + (time_value * 60)) | timestamp_custom('%H:%M', local=False) }}"
                - conditions: "{{ time_unit == 'uren' or time_unit == 'uur' }}"
                  sequence:
                    - service: alarm_control_panel.set_alarm
                      target:
                        entity_id: alarm_control_panel.alarm_panel # VERVANG DIT!
                      data:
                        time: "{{ (now_timestamp + (time_value * 3600)) | timestamp_custom('%H:%M', local=False) }}"
                - conditions: "{{ time_unit == 'seconden' or time_unit == 'seconde' }}"
                  sequence:
                    - service: alarm_control_panel.set_alarm
                      target:
                        entity_id: alarm_control_panel.alarm_panel # VERVANG DIT!
                      data:
                        time: "{{ (now_timestamp + time_value) | timestamp_custom('%H:%M', local=False) }}"
                - conditions: true
                  sequence:
                    - service: notify.persistent_notification
                      data:
                        message: "Ongeldige tijdseenheid. Gebruik 'minuten', 'uren' of 'seconden'."
                        title: "Wekker Notificatie"
            - if:
                - condition: template
                  value_template: "{{ (now_timestamp + (time_value * 60)) | timestamp_custom('%H:%M', local=False) < now().timestamp() | timestamp_custom('%H:%M', local=False) }}"
                - then:
                    - service: notify.persistent_notification
                      data:
                        message: "De ingestelde tijd is in het verleden. Controleer de tijd en probeer het opnieuw."
                        title: "Wekker Notificatie"
        - conditions: true
          sequence:
            - service: alarm_control_panel.set_alarm
              target:
                entity_id: alarm_control_panel.alarm_panel # VERVANG DIT!
              data:
                time: "{{ trigger.time }}"
    mode: single