blueprint:
  name: Alarm Clock Media Player
  description: Plays a local media file when the alarm clock is triggered
  domain: automation
  input:
    alarm_sensor:
      name: Alarm Status Sensor
      description: The alarm clock status sensor to monitor
      selector:
        entity:
          integration: alarm_clock
          domain: sensor
    media_player:
      name: Media Player
      description: Media player to play the alarm sound
      selector:
        entity:
          domain: media_player
    media_file:
      name: Media File
      description: Local media file (e.g., wekker.mp3)
      default: "wekker.mp3"
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input alarm_sensor
    to: "triggered"

action:
  - service: media_player.play_media
    target:
      entity_id: !input media_player
    data:
      media_content_id: !expand
        media-source://media_source/local/{{ media_file }}
      media_content_type: audio/mpeg
    metadata:
      title: !input media_file
      thumbnail: null
      media_class: music
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source

mode: single